### PR TITLE
Added the project specification document

### PR DESCRIPTION
**Pull request by hirwajeaneric**
In this document is a summary of what we the project will do and how it will work.

### CODE REVIEW

**Comment by hirwajeaneric** [comment]
Hello, inviting you to participate in giving me more ideas about what we shall put in this document. I have already written the system description, now let's talk about the main features of the system.

You are welcome to use GitHub and make comments.

More over, you can even see what was already done in the above tab **Files Changed**

If you guys need help, let me know.

**Comment by hirwajeaneric** [comment]
Here are the system features I was thinking of including in the system.

### System features:
1. Landing page
2. Sign in form
3. Login form or login section in the landing page for those who have accounts.
4. Send Cargo: (This is a page with a multi-step form where a client will be filling information regarding their cargo, the destination, the cargo location,...)
	The steps of the form:
	a. User Information: 
		First name, 
		last name, 
		gender,
		email address, 
		phone number, 
		date of birth, 	
	b. User/Cargo Location: 
		Country, 
		District/City,
		postal code, 
		Street Address, 
		House number
	c. Cargo Description: 
		Cargo name, 
		size(length, width), 
		weight, 
		category, 
		description, 
		perishable/non-perishable.
	d. Reciever Information
		First name, 
		last name,
		gender, 
		email address, 
		phone number, 
		date of birth, 			
	e. Destination/Reciever address: 
		When do should it be taken, 
		Country, 
		District/City, 
		postal code,
		Street Address, 
		House number		
	f. Payment information:
		According to information specified above about the cargo size, weight, type, ... the system shall be automaically generating the price it shall take the user to send that cargo.	
		Credit card number
		.......

5. Response page (For a successful transaction)
6. Response page (For successful account registration)
7. User Account page (Where the user will be finding all their information including:
	a. Account information)
	b. Cargo that they send + The progress
	c. ....
	d. Other Commands like:
		- Logout
		- Modify account,...
8. About Page
9. Contact Page
10. Services Page

**Comment by hirwajeaneric** [comment]
12. The dashboard: Reserved for the system managers.

-           To view request sent by users, etc

**Comment by kayihuraemmanuel** [comment]
Dear Hirwa,

I think on the landing page we would have also types which will be grouped together

Example:
                                              **This is for Foreign to Foreign**
-  Ocean Import / Export ---> on this we will charge customers small amount of money since it will take days and it will be in 
                                               Intermodal container                                               
- AIR FREIGHT FORWARDING --> on this we will charge most amount because it will take few hours or days and user air

                                                    **This is for Domestic** 
                                                    
- HOUSEHOLD GOODS & AUTOS --> This is like when a family want to shift or buys goods and wants to be delivered by us



I think we will meet and share more ideas on these 

Thanks

**Comment by hirwajeaneric** [comment]
Good Idea

> Dear Hirwa,
> 
> I think on the landing page we would have also types which will be grouped together
> 
> Example: **This is for Foreign to Foreign**
> 
> * Ocean Import / Export ---> on this we will charge customers small amount of money since it will take days and it will be in
>   Intermodal container
> * AIR FREIGHT FORWARDING --> on this we will charge most amount because it will take few hours or days and user air
>   ```
>                                                 **This is for Domestic** 
>   ```
> * HOUSEHOLD GOODS & AUTOS --> This is like when a family want to shift or buys goods and wants to be delivered by us
> 
> I think we will meet and share more ideas on these
> 
> Thanks

Good Idea,
So you mean that these 3 could be like the different types of services or transfer modes we would be offering?

**Comment by hirwajeaneric** [comment]
I will add it as well

> Good Idea
> 
> > Dear Hirwa,
> > I think on the landing page we would have also types which will be grouped together
> > Example: **This is for Foreign to Foreign**
> > 
> > * Ocean Import / Export ---> on this we will charge customers small amount of money since it will take days and it will be in
> >   Intermodal container
> > * AIR FREIGHT FORWARDING --> on this we will charge most amount because it will take few hours or days and user air
> >   ```
> >                                                 **This is for Domestic** 
> >   ```
> > * HOUSEHOLD GOODS & AUTOS --> This is like when a family want to shift or buys goods and wants to be delivered by us
> > 
> > I think we will meet and share more ideas on these
> > Thanks
> 
> Good Idea, So you mean that these 3 could be like the different types of services or transfer modes we would be offering?

I will add it too.

**Pull request merged**
